version: '3'
services: 
  jupyterlab:
    build: .
    image: jupyterlab-test-img
    container_name: jupyterlab-test
    working_dir: /src
    volumes:
      - ./src:/src
    ports:
      - "8888:8888"
      - "5000:5000"
    command: jupyter-lab --ip 0.0.0.0 --allow-root -b localhost
